file=open("test.txt","w+")
string=input("Enter an input to enter into the file:")
file.write(string+"\n")
lst=[]
num=int(input("Enter the number of words you want to enter into the file:"))
for _ in range(0,num):
    string=input("Enter the word:")
    lst.append(string+"\n")
file.writelines(lst)
file.seek(0)
print("Reading all lines:")
file.seek(0)
line=file.read()
print(line)
file.seek(0)
lines=file.readline()
print(lines)
file.seek(0)
lst=file.readlines()
print(lst)
file.close()